[ 2019-07-03 04:11:59,979 ]  DEBUG  connectionpool.py      :: Starting new HTTP connection (1): 192.168.100.133:8888
[ 2019-07-03 04:12:00,007 ]  DEBUG  connectionpool.py      :: Starting new HTTP connection (1): 192.168.100.133:8888
[ 2019-07-03 04:12:41,696 ]  INFO  main.py      :: storing created Entity from file
[ 2019-07-03 04:12:41,706 ]  INFO  main.py      :: Clossing the file
[ 2019-07-03 04:12:41,849 ]  INFO  _internal.py      ::  * Running on http://0.0.0.0:8888/ (Press CTRL+C to quit)
[ 2019-07-03 04:12:41,852 ]  INFO  _internal.py      ::  * Restarting with stat
[ 2019-07-03 04:12:42,127 ]  INFO  main.py      :: storing created Entity from file
[ 2019-07-03 04:12:42,128 ]  INFO  main.py      :: Clossing the file
[ 2019-07-03 04:12:42,138 ]  WARNING  _internal.py      ::  * Debugger is active!
[ 2019-07-03 04:12:42,142 ]  INFO  _internal.py      ::  * Debugger PIN: 177-254-971
[ 2019-07-03 04:13:22,364 ]  DEBUG  connectionpool.py      :: Starting new HTTP connection (1): 192.168.100.133:8888
[ 2019-07-03 04:13:22,368 ]  INFO  main.py      :: notify data{u'originator': u'', u'subscriptionId': u'd0c08d50-6296-4ef3-9b0f-ff48b3cd5528', u'contextResponses': [{u'contextElement': {u'attributes': [{u'contextValue': 34, u'type': u'float', u'name': u'tempo'}], u'entityId': {u'type': u'Tempr', u'id': u'Temprature702'}, u'domainMetadata': [{u'type': u'point', u'name': u'location', u'value': {u'latitude': 49.406393, u'longitude': 8.684208}}]}, u'statusCode': {u'code': 200, u'reasonPhrase': u'OK'}}]}
[ 2019-07-03 04:13:22,369 ]  INFO  ld_generate.py      :: Start converting ngsiv1 data to NGSI-LD
[ 2019-07-03 04:13:22,369 ]  INFO  ld_generate.py      :: Start converting metadata of ngsiv1 to ngsi-ld metadata
[ 2019-07-03 04:13:22,369 ]  INFO  ld_generate.py      :: Data has been converted to NGSI-LD
[ 2019-07-03 04:13:22,369 ]  INFO  main.py      :: Data is converted to ngsi-ld
[ 2019-07-03 04:13:22,369 ]  INFO  ld_generate.py      :: Creating Entity
[ 2019-07-03 04:13:22,370 ]  INFO  ld_generate.py      :: Entity has been created
[ 2019-07-03 04:13:22,381 ]  INFO  config.py      :: Retriving url of ngsi-ld-broker from config.ini
[ 2019-07-03 04:13:22,382 ]  INFO  main.py      :: sending update request
[ 2019-07-03 04:13:22,386 ]  DEBUG  connectionpool.py      :: Starting new HTTP connection (1): 180.179.214.221:9090
[ 2019-07-03 04:13:23,400 ]  DEBUG  connectionpool.py      :: http://180.179.214.221:9090 "POST /ngsi-ld/v1/entities/urn:ngsi-ld:Temprature702/attrs HTTP/1.1" 404 None
[ 2019-07-03 04:13:23,405 ]  DEBUG  connectionpool.py      :: Starting new HTTP connection (1): 180.179.214.221:9090
[ 2019-07-03 04:13:23,459 ]  DEBUG  connectionpool.py      :: http://180.179.214.221:9090 "PATCH /ngsi-ld/v1/entities/urn:ngsi-ld:Temprature702/attrs HTTP/1.1" 404 None
[ 2019-07-03 04:13:23,460 ]  INFO  rest_client.py      :: Response is None Entity there may some problem in entity
[ 2019-07-03 04:13:23,513 ]  INFO  _internal.py      :: 192.168.100.133 - - [03/Jul/2019 04:13:23] "POST /notifyContext HTTP/1.1" 500 -
[ 2019-07-03 04:13:23,514 ]  DEBUG  connectionpool.py      :: http://192.168.100.133:8888 "POST /notifyContext HTTP/1.1" 500 None
[ 2019-07-03 04:13:23,523 ]  DEBUG  connectionpool.py      :: Starting new HTTP connection (1): 192.168.100.133:8888
[ 2019-07-03 04:13:23,526 ]  INFO  main.py      :: notify data{u'subscriptionId': u'5d09cdeb0016e878cf94e070', u'data': [{u'type': u'roomie', u'id': u'Room5', u'temp': {u'type': u'Float', u'value': 50, u'metadata': {}}}]}
[ 2019-07-03 04:13:23,527 ]  INFO  orian_ld_genrate.py      :: Start converting ngsiv2 data to NGSI-LD
[ 2019-07-03 04:13:23,527 ]  INFO  orian_ld_genrate.py      :: Data has been converted to NGSI-LD
[ 2019-07-03 04:13:23,527 ]  INFO  main.py      :: Data is converted to ngsi-ld
[ 2019-07-03 04:13:23,527 ]  INFO  orian_ld_genrate.py      :: Creating Entity
[ 2019-07-03 04:13:23,528 ]  INFO  orian_ld_genrate.py      :: Entity has been created
[ 2019-07-03 04:13:23,528 ]  INFO  config.py      :: Retriving url of ngsi-ld-broker from config.ini
[ 2019-07-03 04:13:23,528 ]  INFO  main.py      :: sending update request
[ 2019-07-03 04:13:23,531 ]  DEBUG  connectionpool.py      :: Starting new HTTP connection (1): 180.179.214.221:9090
[ 2019-07-03 04:13:23,560 ]  DEBUG  connectionpool.py      :: http://180.179.214.221:9090 "POST /ngsi-ld/v1/entities/urn:ngsi-ld:Room5/attrs HTTP/1.1" 404 None
[ 2019-07-03 04:13:23,564 ]  DEBUG  connectionpool.py      :: Starting new HTTP connection (1): 180.179.214.221:9090
[ 2019-07-03 04:13:23,591 ]  DEBUG  connectionpool.py      :: http://180.179.214.221:9090 "PATCH /ngsi-ld/v1/entities/urn:ngsi-ld:Room5/attrs HTTP/1.1" 404 None
[ 2019-07-03 04:13:23,592 ]  INFO  rest_client.py      :: Response is None Entity there may some problem in entity
[ 2019-07-03 04:13:23,617 ]  INFO  _internal.py      :: 192.168.100.133 - - [03/Jul/2019 04:13:23] "POST /notifyContext1 HTTP/1.1" 500 -
[ 2019-07-03 04:13:23,618 ]  DEBUG  connectionpool.py      :: http://192.168.100.133:8888 "POST /notifyContext1 HTTP/1.1" 500 None
[ 2019-07-03 04:19:48,491 ]  INFO  main.py      :: storing created Entity from file
[ 2019-07-03 04:19:48,492 ]  INFO  main.py      :: Clossing the file
[ 2019-07-03 04:19:48,505 ]  INFO  _internal.py      ::  * Running on http://0.0.0.0:8888/ (Press CTRL+C to quit)
[ 2019-07-03 04:19:48,506 ]  INFO  _internal.py      ::  * Restarting with stat
[ 2019-07-03 04:19:48,785 ]  INFO  main.py      :: storing created Entity from file
[ 2019-07-03 04:19:48,785 ]  INFO  main.py      :: Clossing the file
[ 2019-07-03 04:19:48,796 ]  WARNING  _internal.py      ::  * Debugger is active!
[ 2019-07-03 04:19:48,797 ]  INFO  _internal.py      ::  * Debugger PIN: 177-254-971
[ 2019-07-03 04:21:10,596 ]  INFO  main.py      :: storing created Entity from file
[ 2019-07-03 04:21:10,596 ]  INFO  main.py      :: Clossing the file
[ 2019-07-03 04:21:10,609 ]  INFO  _internal.py      ::  * Running on http://0.0.0.0:8888/ (Press CTRL+C to quit)
[ 2019-07-03 04:21:10,610 ]  INFO  _internal.py      ::  * Restarting with stat
[ 2019-07-03 04:21:10,899 ]  INFO  main.py      :: storing created Entity from file
[ 2019-07-03 04:21:10,899 ]  INFO  main.py      :: Clossing the file
[ 2019-07-03 04:21:10,910 ]  WARNING  _internal.py      ::  * Debugger is active!
[ 2019-07-03 04:21:10,911 ]  INFO  _internal.py      ::  * Debugger PIN: 177-254-971
[ 2019-07-03 04:26:05,074 ]  INFO   main.py        storing created Entity from file
[ 2019-07-03 04:26:05,075 ]  INFO   main.py        Clossing the file
[ 2019-07-03 04:26:05,087 ]  INFO   _internal.py         * Running on http://0.0.0.0:8888/ (Press CTRL+C to quit)
[ 2019-07-03 04:26:05,088 ]  INFO   _internal.py         * Restarting with stat
[ 2019-07-03 04:26:05,371 ]  INFO   main.py        storing created Entity from file
[ 2019-07-03 04:26:05,372 ]  INFO   main.py        Clossing the file
[ 2019-07-03 04:26:05,382 ]  WARNING   _internal.py         * Debugger is active!
[ 2019-07-03 04:26:05,383 ]  INFO   _internal.py         * Debugger PIN: 177-254-971
